"use client";

import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Compass, X } from "lucide-react";

type Path = { title: string; icon: string; roles: string[]; skills: string[]; why: string; start: string[]; weeks: string[] };
const paths: Path[] = [
  { title: "Full Stack Development", icon: "💻", roles: ["Frontend Developer", "Backend Developer", "Full Stack Developer"], skills: ["HTML + CSS", "JavaScript", "React", "Node.js", "Databases", "APIs"], why: "You enjoy building applications and exploring web technology.", start: ["Computer & internet basics", "Programming fundamentals", "HTML + CSS", "JavaScript", "Build your first website"], weeks: ["HTML and web basics", "CSS and responsive design", "JavaScript fundamentals", "Build your first website"] },
  { title: "Data & Analytics", icon: "📊", roles: ["Data Analyst", "BI Analyst", "Junior Data Scientist"], skills: ["Python", "SQL", "Statistics", "Pandas", "Visualization", "Projects"], why: "You are curious about patterns, evidence, and data-driven decisions.", start: ["Python basics", "SQL fundamentals", "Spreadsheets and data", "Statistics", "Analyze a real dataset"], weeks: ["Python and data types", "SQL and querying", "Charts and storytelling", "Analyze a public dataset"] },
  { title: "AI / Machine Learning", icon: "🤖", roles: ["ML Engineer", "AI Developer", "Data Scientist"], skills: ["Python", "Maths", "Statistics", "Machine Learning", "Deep Learning", "AI Projects"], why: "Your answers point toward intelligent systems and problem solving.", start: ["Python basics", "Maths and logic", "Statistics", "Machine learning basics", "Build a small model"], weeks: ["Python foundations", "Maths and statistics", "Your first ML model", "Evaluate and explain results"] },
  { title: "Cybersecurity", icon: "🔐", roles: ["Security Analyst", "SOC Analyst", "Application Security Engineer"], skills: ["Networking", "Linux", "Security basics", "Web security", "Cryptography", "Security tools"], why: "You like understanding systems and solving technical problems safely.", start: ["Computer basics", "Networking", "Linux", "Security fundamentals", "Practice in a safe lab"], weeks: ["Networking concepts", "Linux and systems", "Common web risks", "Document a safe security lab"] },
];

export default function CareerDiscovery() {
  const [open, setOpen] = useState(false); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]); const [selected, setSelected] = useState<Path>();
  const questions = [
    ["Where are you starting from?", ["Completely New", "Beginner", "I know basic programming", "Intermediate", "I already have some projects"]],
    ["What sounds interesting to you?", ["Websites & Web Apps", "Artificial Intelligence", "Data & Analytics", "Cybersecurity", "Cloud & DevOps", "Software Development", "Not sure"]],
    ["Which type of work sounds most interesting?", ["I like building things", "I like finding patterns in data", "I like solving technical problems", "I like designing things", "I am not sure yet"]],
    ["How comfortable are you with Maths and logical problem solving?", ["Low", "Moderate", "Good", "Very Good", "Not sure"]],
    ["What kind of work would you like?", ["Build applications", "Analyse data", "Work with AI", "Secure systems", "Design user interfaces", "I am not sure"]],
    ["What is your current goal?", ["Get an internship", "Get a job", "Become a software developer", "Build my own projects", "Explore technology first", "I am not sure"]],
    ["How much time can you regularly spend learning?", ["30 minutes/day", "1 hour/day", "2 hours/day", "3+ hours/day", "Depends on my schedule"]],
  ] as [string, string[]][];
  const recommended = useMemo(() => { const joined = answers.join(" ").toLowerCase(); if (joined.includes("data") || joined.includes("patterns")) return [paths[1], paths[2], paths[0]]; if (joined.includes("ai")) return [paths[2], paths[0], paths[1]]; if (joined.includes("secure") || joined.includes("cyber")) return [paths[3], paths[0], paths[2]]; return [paths[0], paths[1], paths[2]]; }, [answers]);
  function choose(value: string) { const next = [...answers]; next[step] = value; setAnswers(next); if (step === questions.length - 1) { setSelected(recommended[0]); setOpen(false); } else setStep(step + 1); }
  if (open) return <div className="mt-8 rounded-2xl border border-violet-400/30 bg-[#12162a] p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-violet-300">Career discovery · Step {step + 1} of {questions.length}</p><h2 className="mt-2 text-2xl font-bold">{questions[step][0]}</h2></div><button onClick={() => setOpen(false)} aria-label="Close discovery"><X/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{questions[step][1].map((option) => <button key={option} onClick={() => choose(option)} className="rounded-xl border border-white/10 bg-white/[.04] p-4 text-left text-sm hover:border-violet-400 hover:bg-violet-500/10">{option}<ArrowRight className="float-right text-slate-500" size={16}/></button>)}</div><div className="mt-6 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{ width: `${((step + 1) / questions.length) * 100}%` }}/></div></div>;
  if (selected) return <section className="mt-8 rounded-2xl border border-violet-400/30 bg-white/[.04] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-violet-300">Your Career Paths</p><h2 className="mt-1 text-2xl font-bold">Based on your answers</h2><p className="mt-2 text-sm text-slate-400">These are guidance signals, not guaranteed outcomes.</p></div><button onClick={() => { setSelected(undefined); setStep(0); setAnswers([]); setOpen(true); }} className="text-sm text-cyan-300 hover:text-white">Retake discovery</button></div><div className="mt-6 grid gap-4 lg:grid-cols-3">{recommended.map((path, index) => <button key={path.title} onClick={() => setSelected(path)} className={`rounded-2xl border p-5 text-left ${path.title === selected.title ? "border-violet-400 bg-violet-500/10" : "border-white/10 bg-white/[.03]"}`}><span className="text-3xl">{path.icon}</span><h3 className="mt-3 font-semibold">{path.title}</h3><p className="mt-2 text-xs text-slate-400">Interest alignment: {88 - index * 7}%</p><p className="mt-3 text-sm text-slate-400">{path.why}</p></button>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div><h3 className="font-semibold">Why this path?</h3><p className="mt-2 text-sm text-slate-400">✓ {selected.why}</p><p className="mt-4 text-sm font-medium">Possible roles</p><div className="mt-2 flex flex-wrap gap-2">{selected.roles.map((role) => <span className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-300" key={role}>{role}</span>)}</div><p className="mt-5 text-sm font-medium">Required skills</p><div className="mt-2 flex flex-wrap gap-2">{selected.skills.map((skill) => <span className="rounded-full bg-violet-400/10 px-3 py-1 text-xs text-violet-200" key={skill}>{skill}</span>)}</div></div><div className="rounded-2xl border border-white/10 bg-black/10 p-5"><h3 className="font-semibold">Your Starting Point</h3><ol className="mt-3 space-y-2 text-sm text-slate-300">{selected.start.map((item, index) => <li key={item}><span className="mr-2 text-violet-300">{index + 1}.</span>{item}</li>)}</ol><h3 className="mt-6 font-semibold">Your First 30 Days</h3><div className="mt-3 space-y-2 text-sm text-slate-400">{selected.weeks.map((item, index) => <p key={item}><span className="mr-2 text-cyan-300">Week {index + 1}</span>{item}</p>)}</div><button onClick={() => { window.location.href = "/roadmap"; }} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-violet-500 py-3 text-sm font-semibold">Start Existing Roadmap <ArrowRight size={16}/></button></div></div></section>;
  return <section className="mt-8 rounded-2xl border border-cyan-400/20 bg-gradient-to-br from-cyan-400/10 to-violet-500/10 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="mb-2 flex items-center gap-2 text-sm text-cyan-300"><Compass size={16}/> New to technology?</p><h2 className="text-2xl font-bold">Not sure where to start?</h2><p className="mt-2 max-w-xl text-sm text-slate-400">Tell us a little about yourself and we'll help you discover suitable technical career paths.</p></div><button onClick={() => setOpen(true)} className="flex w-fit items-center gap-2 rounded-xl bg-violet-500 px-5 py-3 text-sm font-semibold">Find My Career Path <ArrowRight size={16}/></button></div><div className="mt-5 flex flex-wrap gap-3 text-xs text-slate-400"><span><CheckCircle2 className="mr-1 inline text-emerald-300" size={14}/>Beginner friendly</span><span><CheckCircle2 className="mr-1 inline text-emerald-300" size={14}/>Explore before choosing</span><span><CheckCircle2 className="mr-1 inline text-emerald-300" size={14}/>Connects to your roadmap</span></div></section>;
}
