"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, LockKeyhole, Sparkles } from "lucide-react";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
const demoEmail = "student@nxtrot.local";
const demoPassword = "Student@123";

export default function LoginPage() {
  const [mode, setMode] = useState<"login" | "signup">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(demoEmail); const [password, setPassword] = useState(demoPassword); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`${api}/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify(mode === "login" ? { email, password } : { name, email, password, role: "STUDENT" }) }); const data = await response.json() as { message?: string }; if (!response.ok) throw new Error(data.message ?? "Unable to authenticate"); window.location.assign("/"); } catch (err) { setError(err instanceof Error ? err.message : "Unable to authenticate"); } finally { setLoading(false); } }
  function useDemo() { setMode("login"); setEmail(demoEmail); setPassword(demoPassword); setError(""); }
  return <main className="flex min-h-screen items-center justify-center bg-[#090b16] p-5 text-white"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.05] p-8 shadow-2xl backdrop-blur-xl"><div className="mb-8 flex items-center gap-3"><div className="rounded-xl bg-violet-500 p-2"><Sparkles size={20}/></div><div><p className="text-xl font-bold">SkillSync<span className="text-violet-300"> AI</span></p><p className="text-xs text-slate-500">Industry readiness platform</p></div></div><h1 className="text-2xl font-bold">{mode === "login" ? "Welcome back" : "Create your account"}</h1><p className="mt-2 text-sm text-slate-400">{mode === "login" ? "Continue your path to industry readiness." : "Build your verified skill profile."}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode === "signup" && <input required value={name} onChange={(event) => setName(event.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-violet-400" placeholder="Full name"/>}<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-violet-400" placeholder="Email address"/><div className="relative"><LockKeyhole className="absolute left-3 top-3 text-slate-500" size={17}/><input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 py-3 pl-10 pr-4 text-sm outline-none focus:border-violet-400" placeholder="Password"/></div>{error && <p className="rounded-lg bg-rose-400/10 p-3 text-sm text-rose-300">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet-500 py-3 text-sm font-semibold disabled:opacity-60">{loading ? "Please wait..." : mode === "login" ? "Log in" : "Create account"}<ArrowRight size={16}/></button></form>{mode === "login" && <button onClick={useDemo} className="mt-4 w-full rounded-xl border border-cyan-400/30 bg-cyan-400/10 py-3 text-sm text-cyan-200 hover:bg-cyan-400/20">Use demo student · student@nxtrot.local</button>}<button onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); }} className="mt-6 w-full text-sm text-slate-400 hover:text-white">{mode === "login" ? "New to SkillSync? Create an account" : "Already have an account? Log in"}</button></div></main>;
}
