import "dotenv/config";
import "express-async-errors";
import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import multer from "multer";
import fs from "node:fs";
import path from "node:path";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import { PrismaClient, Role } from "@prisma/client";
import { communityPostSchema, communityReplySchema, loginSchema, signupSchema } from "@skillsync/shared";

const prisma = new PrismaClient(); const app = express();
const runFile = promisify(execFile) as unknown as (file: string, args: string[], options: { cwd?: string; input: string; timeout: number; maxBuffer: number }) => Promise<{ stdout: string; stderr: string }>;
app.use(cors({ origin: true, credentials: true })); app.use(express.json());
app.get("/", (_req, res) => res.json({ service: "skillsync-api", status: "ok", health: "/api/health" }));
const secret = process.env.JWT_SECRET ?? "development-secret-change-me";
const refreshSecret = process.env.JWT_REFRESH_SECRET ?? "development-refresh-secret-change-me";
const signRefresh = (id: string, role: Role) => jwt.sign({ sub: id, role }, refreshSecret, { expiresIn: "7d" });
const setAuthCookies = (res: express.Response, user: { id: string; role: Role }) => { const access = sign(user.id, user.role); const refresh = signRefresh(user.id, user.role); res.setHeader("Set-Cookie", [`accessToken=${access}; HttpOnly; Path=/; SameSite=Lax; Max-Age=900`, `refreshToken=${refresh}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800`]); };
const cookieValue = (req: express.Request, name: string) => req.headers.cookie?.split(";").map((item) => item.trim()).find((item) => item.startsWith(`${name}=`))?.slice(name.length + 1);
const requestCounts = new Map<string, { count: number; resetAt: number }>();
app.use((req, res, next) => { const key = req.ip ?? "unknown"; const now = Date.now(); const entry = requestCounts.get(key); if (!entry || entry.resetAt <= now) requestCounts.set(key, { count: 1, resetAt: now + 60_000 }); else { entry.count += 1; if (entry.count > 120) return res.status(429).json({ message: "Too many requests. Try again shortly." }); } res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("X-Frame-Options", "DENY"); next(); });
app.use((req, _res, next) => { if (process.env.NODE_ENV !== "test") console.log(JSON.stringify({ method: req.method, path: req.path, at: new Date().toISOString() })); next(); });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024 } });
const sign = (id: string, role: Role) => jwt.sign({ sub: id, role }, secret, { expiresIn: "15m" });
type LocalUser = { id: string; name: string; email: string; passwordHash: string; role: Role };
const localStorePath = path.join(process.cwd(), "data", "local-store.json");
const loadLocalUsers = () => { try { const raw = fs.readFileSync(localStorePath, "utf8"); return new Map<string, LocalUser>(Object.entries(JSON.parse(raw) as Record<string, LocalUser>)); } catch { return new Map<string, LocalUser>(); } };
const localUsers = loadLocalUsers();
const saveLocalUsers = () => { fs.mkdirSync(path.dirname(localStorePath), { recursive: true }); fs.writeFileSync(localStorePath, JSON.stringify(Object.fromEntries(localUsers), null, 2)); };
type LocalCommunityPost = { id: string; authorId: string; content: string; createdAt: string; updatedAt: string; likes: string[]; replies: Array<{ id: string; authorId: string; content: string; createdAt: string }> };
const communityStorePath = path.join(process.cwd(), "data", "community-store.json");
const loadCommunityPosts = () => { try { return JSON.parse(fs.readFileSync(communityStorePath, "utf8")) as LocalCommunityPost[]; } catch { return []; } };
let localCommunityPosts = loadCommunityPosts();
const saveCommunityPosts = () => { fs.mkdirSync(path.dirname(communityStorePath), { recursive: true }); fs.writeFileSync(communityStorePath, JSON.stringify(localCommunityPosts, null, 2)); };
const localAuthor = (id: string) => { const user = [...localUsers.values()].find((item) => item.id === id); return { id, name: user?.name ?? (id === "demo-student" ? "Demo Student" : "SkillSync Student") }; };
const localPostShape = (post: LocalCommunityPost, userId: string) => ({ id: post.id, content: post.content, createdAt: post.createdAt, updatedAt: post.updatedAt, author: localAuthor(post.authorId), replyCount: post.replies.length, likeCount: post.likes.length, liked: post.likes.includes(userId) });
const localAuthFallback = async (req: express.Request, res: express.Response, next: express.NextFunction) => {
  if (process.env.DATABASE_URL) return next();
  if (req.path === "/api/auth/signup" && req.method === "POST") { const data = signupSchema.parse(req.body); if (localUsers.has(data.email)) return res.status(409).json({ message: "Email already registered" }); const user: LocalUser = { id: `local-${Date.now()}`, name: data.name, email: data.email, passwordHash: await bcrypt.hash(data.password, 12), role: data.role }; localUsers.set(user.email, user); saveLocalUsers(); setAuthCookies(res, user); return res.status(201).json({ user: { id: user.id, name: user.name, email: user.email, role: user.role } }); }
  if (req.path === "/api/auth/login" && req.method === "POST") { const data = loginSchema.parse(req.body); let user = localUsers.get(data.email); if (!user && data.email === "student@nxtrot.local" && data.password === "Student@123") { user = { id: "demo-student", name: "Demo Student", email: data.email, passwordHash: await bcrypt.hash(data.password, 12), role: "STUDENT" }; localUsers.set(user.email, user); saveLocalUsers(); } if (!user || !(await bcrypt.compare(data.password, user.passwordHash))) return res.status(401).json({ message: "Invalid credentials" }); setAuthCookies(res, user); return res.json({ user: { id: user.id, name: user.name, email: user.email, role: user.role } }); }
  if (req.path === "/api/auth/me" && req.method === "GET") { const token = cookieValue(req, "accessToken"); if (!token) return res.status(401).json({ message: "Authentication required" }); try { const payload = jwt.verify(token, secret) as { sub: string }; const user = [...localUsers.values()].find((item) => item.id === payload.sub); if (!user) return res.status(401).json({ message: "Session invalid" }); return res.json({ user: { id: user.id, name: user.name, email: user.email, role: user.role } }); } catch { return res.status(401).json({ message: "Session expired" }); } }
  if (req.path === "/api/auth/refresh" && req.method === "POST") { const token = cookieValue(req, "refreshToken"); if (!token) return res.status(401).json({ message: "Refresh token missing" }); try { const payload = jwt.verify(token, refreshSecret) as { sub: string }; const user = [...localUsers.values()].find((item) => item.id === payload.sub); if (!user) return res.status(401).json({ message: "Session invalid" }); setAuthCookies(res, user); return res.json({ refreshed: true }); } catch { return res.status(401).json({ message: "Refresh token expired" }); } }
  return next();
};
app.use(localAuthFallback);
app.get("/api/health", (_req, res) => res.json({ status: "ok", service: "skillsync-api" }));
app.use("/api/community", (req, res, next) => { if (process.env.DATABASE_URL) return next(); const userId = userIdFromRequest(req); const postMatch = req.path.match(/^\/posts\/([^/]+)$/); const replyMatch = req.path.match(/^\/posts\/([^/]+)\/replies$/); const likeMatch = req.path.match(/^\/posts\/([^/]+)\/like$/); if (req.path === "/posts" && req.method === "GET") return res.json({ posts: [...localCommunityPosts].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map((post) => localPostShape(post, userId)) }); if (req.path === "/posts" && req.method === "POST") { const parsed = communityPostSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Content is required and must be at most 2000 characters" }); const now = new Date().toISOString(); const post: LocalCommunityPost = { id: `community-${Date.now()}`, authorId: userId, content: parsed.data.content, createdAt: now, updatedAt: now, likes: [], replies: [] }; localCommunityPosts = [post, ...localCommunityPosts]; saveCommunityPosts(); return res.status(201).json({ post: localPostShape(post, userId) }); } if (replyMatch && req.method === "GET") { const post = localCommunityPosts.find((item) => item.id === replyMatch[1]); if (!post) return res.status(404).json({ message: "Post not found" }); return res.json({ replies: post.replies.map((reply) => ({ ...reply, author: localAuthor(reply.authorId) })) }); } if (replyMatch && req.method === "POST") { const parsed = communityReplySchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Content is required and must be at most 2000 characters" }); const post = localCommunityPosts.find((item) => item.id === replyMatch[1]); if (!post) return res.status(404).json({ message: "Post not found" }); const reply = { id: `reply-${Date.now()}`, authorId: userId, content: parsed.data.content, createdAt: new Date().toISOString() }; post.replies.push(reply); saveCommunityPosts(); return res.status(201).json({ reply: { ...reply, author: localAuthor(userId) } }); } if (likeMatch && req.method === "POST") { const post = localCommunityPosts.find((item) => item.id === likeMatch[1]); if (!post) return res.status(404).json({ message: "Post not found" }); const index = post.likes.indexOf(userId); if (index >= 0) post.likes.splice(index, 1); else post.likes.push(userId); saveCommunityPosts(); return res.json({ liked: index < 0, likeCount: post.likes.length }); } if (postMatch && req.method === "GET") return res.status(404).json({ message: "Post not found" }); return next(); });
const communityPostShape = (post: { id: string; content: string; createdAt: Date; updatedAt: Date; author: { id: string; name: string }; _count: { replies: number; likes: number }; likes: Array<{ userId: string }> }, userId: string) => ({ id: post.id, content: post.content, createdAt: post.createdAt, updatedAt: post.updatedAt, author: post.author, replyCount: post._count.replies, likeCount: post._count.likes, liked: post.likes.some((like) => like.userId === userId) });
app.get("/api/community/posts", async (req, res) => { const userId = userIdFromRequest(req); const posts = await prisma.communityPost.findMany({ orderBy: { createdAt: "desc" }, take: 50, include: { author: { select: { id: true, name: true } }, replies: { select: { id: true } }, likes: { select: { userId: true } }, _count: { select: { replies: true, likes: true } } } }); res.json({ posts: posts.map((post) => communityPostShape(post, userId)) }); });
app.post("/api/community/posts", async (req, res) => { const parsed = communityPostSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Content is required and must be at most 2000 characters" }); const userId = userIdFromRequest(req); const post = await prisma.communityPost.create({ data: { content: parsed.data.content, authorId: userId }, include: { author: { select: { id: true, name: true } }, replies: { select: { id: true } }, likes: { select: { userId: true } }, _count: { select: { replies: true, likes: true } } } }); res.status(201).json({ post: communityPostShape(post, userId) }); });
app.get("/api/community/posts/:postId/replies", async (req, res) => { const replies = await prisma.communityReply.findMany({ where: { postId: req.params.postId }, orderBy: { createdAt: "asc" }, include: { author: { select: { id: true, name: true } } } }); res.json({ replies }); });
app.post("/api/community/posts/:postId/replies", async (req, res) => { const parsed = communityReplySchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Content is required and must be at most 2000 characters" }); const post = await prisma.communityPost.findUnique({ where: { id: req.params.postId }, select: { id: true } }); if (!post) return res.status(404).json({ message: "Post not found" }); const reply = await prisma.communityReply.create({ data: { postId: post.id, authorId: userIdFromRequest(req), content: parsed.data.content }, include: { author: { select: { id: true, name: true } } } }); res.status(201).json({ reply }); });
app.post("/api/community/posts/:postId/like", async (req, res) => { const userId = userIdFromRequest(req); const post = await prisma.communityPost.findUnique({ where: { id: req.params.postId }, select: { id: true } }); if (!post) return res.status(404).json({ message: "Post not found" }); const existing = await prisma.communityPostLike.findUnique({ where: { postId_userId: { postId: post.id, userId } } }); if (existing) await prisma.communityPostLike.delete({ where: { id: existing.id } }); else await prisma.communityPostLike.create({ data: { postId: post.id, userId } }); const likeCount = await prisma.communityPostLike.count({ where: { postId: post.id } }); res.json({ liked: !existing, likeCount }); });
const languageConfig: Record<string, { image: string; file: string; command: string[] }> = { python: { image: "python:3.12-alpine", file: "main.py", command: ["python", "/workspace/main.py"] }, c: { image: "gcc:14", file: "main.c", command: ["sh", "-lc", "gcc /workspace/main.c -o /tmp/main && /tmp/main"] }, cpp: { image: "gcc:14", file: "main.cpp", command: ["sh", "-lc", "g++ /workspace/main.cpp -o /tmp/main && /tmp/main"] }, java: { image: "eclipse-temurin:21-jdk", file: "Main.java", command: ["sh", "-lc", "javac /workspace/Main.java && java -cp /workspace Main"] } };
const runLocalProcess = (command: string, args: string[], cwd: string, input: string) => new Promise<{ stdout: string; stderr: string }>((resolve, reject) => { const child = spawn(command, args, { cwd, shell: false, windowsHide: true }); let stdout = ""; let stderr = ""; let settled = false; const finish = (callback: () => void) => { if (!settled) { settled = true; callback(); } }; const timer = setTimeout(() => { child.kill(); finish(() => reject(new Error("timed out"))); }, 5000); child.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString(); if (stdout.length > 200_000) child.kill(); }); child.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString(); if (stderr.length > 200_000) child.kill(); }); child.on("error", (error) => { clearTimeout(timer); finish(() => reject(error)); }); child.on("close", (exitCode) => { clearTimeout(timer); finish(() => exitCode === 0 ? resolve({ stdout, stderr }) : reject(new Error(stderr || `Process exited with code ${exitCode}`))); }); child.stdin.write(input); child.stdin.end(); });
const runLocalCode = async (language: string, code: string, input: string) => { const directory = await mkdtemp(`${path.join(os.tmpdir(), "skillsync-code-")}`); try { if (language === "python") { const bundledCandidates = [path.resolve(process.cwd(), "backend", "tools", "python", "python.exe"), path.resolve(process.cwd(), "tools", "python", "python.exe")]; const bundledPython = bundledCandidates.find((candidate) => fs.existsSync(candidate)); if (bundledPython) { await writeFile(path.join(directory, "input.txt"), input, "utf8"); await writeFile(path.join(directory, "runner.py"), `import sys\nsys.stdin = open("input.txt", encoding="utf-8")\n${code}\n`, "utf8"); return runFile(bundledPython, ["runner.py"], { cwd: directory, input: "", timeout: 5000, maxBuffer: 200_000 }); } throw new Error("Python runtime is not installed. Restart the backend from the project root."); } if (language === "c") { await writeFile(path.join(directory, "main.c"), code, "utf8"); await runLocalProcess("gcc", ["main.c", "-O2", "-o", "main.exe"], directory, ""); return runLocalProcess(path.join(directory, "main.exe"), [], directory, input); } if (language === "cpp") { await writeFile(path.join(directory, "main.cpp"), code, "utf8"); await runLocalProcess("g++", ["main.cpp", "-O2", "-o", "main.exe"], directory, ""); return runLocalProcess(path.join(directory, "main.exe"), [], directory, input); } await writeFile(path.join(directory, "Main.java"), code, "utf8"); await runLocalProcess("javac", ["Main.java"], directory, ""); return runLocalProcess("java", ["-cp", directory, "Main"], directory, input); } finally { try { await rm(directory, { recursive: true, force: true }); } catch { setTimeout(() => { void rm(directory, { recursive: true, force: true }).catch(() => undefined); }, 150); } } };
app.post("/api/code/run", async (req, res) => { const { language, code, input = "" } = req.body as { language?: string; code?: string; input?: string }; if (!language || !code || !languageConfig[language]) return res.status(400).json({ message: "Supported language and non-empty code are required" }); if (code.length > 100_000 || input.length > 20_000) return res.status(413).json({ message: "Code or input exceeds the safe size limit" }); const config = languageConfig[language]; const started = Date.now(); const container = `skillsync-run-${Date.now()}`; try { const args = ["run", "--rm", "--name", container, "--network", "none", "--memory", "128m", "--cpus", "0.5", "--pids-limit", "64", "--read-only", "--tmpfs", "/tmp:rw,noexec,nosuid,size=32m", "-i", "-v", `${process.cwd()}:/host:ro`, config.image, ...config.command]; const result = await runFile("docker", args, { input: `${code}\n${input}`, timeout: 5000, maxBuffer: 200_000 }); const executionTime = Date.now() - started; void prisma.codeRun.create({ data: { studentId: userIdFromRequest(req), language, status: "SUCCESS", executionTimeMs: executionTime } }).catch(() => undefined); res.json({ status: "SUCCESS", output: result.stdout, error: result.stderr, executionTime }); } catch (error) { const message = error instanceof Error ? error.message : "Execution failed"; if (message.includes("ENOENT") && process.env.NODE_ENV !== "production") { try { const result = await runLocalCode(language, code, input); const executionTime = Date.now() - started; void prisma.codeRun.create({ data: { studentId: userIdFromRequest(req), language, status: "SUCCESS", executionTimeMs: executionTime } }).catch(() => undefined); return res.json({ status: "SUCCESS", output: result.stdout, error: result.stderr, executionTime, runner: "local-development" }); } catch (localError) { const localMessage = localError instanceof Error ? localError.message : "Local execution failed"; const errorText = localMessage.includes("timed out") ? "Time limit exceeded." : localMessage; const executionTime = Date.now() - started; void prisma.codeRun.create({ data: { studentId: userIdFromRequest(req), language, status: "FAILED", executionTimeMs: executionTime } }).catch(() => undefined); return res.status(422).json({ status: "FAILED", output: "", error: errorText, executionTime, runner: "local-development" }); } } const unavailable = message.includes("ENOENT") ? "Docker is not available. Start Docker Desktop to run code securely." : message.includes("timed out") ? "Time limit exceeded." : "Compilation or runtime error."; const executionTime = Date.now() - started; void prisma.codeRun.create({ data: { studentId: userIdFromRequest(req), language, status: unavailable.includes("Docker") ? "UNAVAILABLE" : "FAILED", executionTimeMs: executionTime } }).catch(() => undefined); res.status(422).json({ status: unavailable.includes("Docker") ? "UNAVAILABLE" : "FAILED", output: "", error: unavailable, executionTime }); } });
app.get("/api/dev/data", (_req, res) => { if (process.env.NODE_ENV === "production") return res.status(404).json({ message: "Not found" }); res.json({ storage: process.env.DATABASE_URL ? "postgresql" : "local-development-store", users: [...localUsers.values()].map(({ passwordHash: _passwordHash, ...user }) => user), note: "Development-only view. Password hashes are intentionally hidden." }); });
const emptyCodeActivity = () => { const heatmap = []; for (let index = 364; index >= 0; index -= 1) { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - index); heatmap.push({ date: date.toISOString().slice(0, 10), count: 0 }); } return { heatmap, currentStreak: 0, longestStreak: 0, totalRuns: 0, successRate: 0, byLanguage: [] }; };
const aggregateCodeActivity = (runs: { language: string; status: string; createdAt: Date }[]) => { const counts = new Map<string, number>(); const languages = new Map<string, number>(); runs.forEach((run) => { const date = run.createdAt.toISOString().slice(0, 10); counts.set(date, (counts.get(date) ?? 0) + 1); languages.set(run.language, (languages.get(run.language) ?? 0) + 1); }); const heatmap = []; for (let index = 364; index >= 0; index -= 1) { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - index); heatmap.push({ date: date.toISOString().slice(0, 10), count: counts.get(date.toISOString().slice(0, 10)) ?? 0 }); } const active = new Set(heatmap.filter((day) => day.count > 0).map((day) => day.date)); const today = new Date(); today.setHours(0, 0, 0, 0); const cursor = active.has(today.toISOString().slice(0, 10)) ? today : new Date(today.getTime() - 86400000); let currentStreak = 0; while (active.has(cursor.toISOString().slice(0, 10))) { currentStreak += 1; cursor.setDate(cursor.getDate() - 1); } let longestStreak = 0; let running = 0; heatmap.forEach((day) => { running = day.count ? running + 1 : 0; longestStreak = Math.max(longestStreak, running); }); return { heatmap, currentStreak, longestStreak, totalRuns: runs.length, successRate: runs.length ? Math.round(runs.filter((run) => run.status === "SUCCESS").length / runs.length * 100) : 0, byLanguage: [...languages.entries()].map(([language, count]) => ({ language, count })) }; };
app.get("/api/code/activity", async (req, res) => { if (!process.env.DATABASE_URL) return res.json(emptyCodeActivity()); const since = new Date(); since.setHours(0, 0, 0, 0); since.setDate(since.getDate() - 364); const runs = await prisma.codeRun.findMany({ where: { studentId: userIdFromRequest(req), createdAt: { gte: since } }, select: { language: true, status: true, createdAt: true }, orderBy: { createdAt: "asc" } }); res.json(aggregateCodeActivity(runs)); });
app.post("/api/auth/signup", async (req, res) => { const data = signupSchema.parse(req.body); const exists = await prisma.user.findUnique({ where: { email: data.email } }); if (exists) return res.status(409).json({ message: "Email already registered" }); const user = await prisma.user.create({ data: { name: data.name, email: data.email, passwordHash: await bcrypt.hash(data.password, 12), role: data.role } }); setAuthCookies(res, user); res.status(201).json({ user: { id: user.id, name: user.name, email: user.email, role: user.role } }); });
app.post("/api/auth/login", async (req, res) => { const data = loginSchema.parse(req.body); const user = await prisma.user.findUnique({ where: { email: data.email } }); if (!user?.passwordHash || !(await bcrypt.compare(data.password, user.passwordHash))) return res.status(401).json({ message: "Invalid credentials" }); setAuthCookies(res, user); res.json({ user: { id: user.id, name: user.name, email: user.email, role: user.role } }); });
app.get("/api/auth/me", async (req, res) => { const token = cookieValue(req, "accessToken"); if (!token) return res.status(401).json({ message: "Authentication required" }); try { const payload = jwt.verify(token, secret) as { sub: string }; const user = await prisma.user.findUnique({ where: { id: payload.sub }, select: { id: true, name: true, email: true, role: true } }); if (!user) return res.status(401).json({ message: "Session invalid" }); res.json({ user }); } catch { res.status(401).json({ message: "Session expired" }); } });
app.post("/api/auth/refresh", async (req, res) => { const token = cookieValue(req, "refreshToken"); if (!token) return res.status(401).json({ message: "Refresh token missing" }); try { const payload = jwt.verify(token, refreshSecret) as { sub: string; role: Role }; const user = await prisma.user.findUnique({ where: { id: payload.sub }, select: { id: true, role: true } }); if (!user) return res.status(401).json({ message: "Session invalid" }); setAuthCookies(res, user); res.json({ refreshed: true }); } catch { res.status(401).json({ message: "Refresh token expired" }); } });
app.post("/api/auth/logout", async (_req, res) => { res.setHeader("Set-Cookie", ["accessToken=; HttpOnly; Path=/; Max-Age=0", "refreshToken=; HttpOnly; Path=/; Max-Age=0"]); res.json({ loggedOut: true }); });
const userIdFromRequest = (req: express.Request) => String(req.headers["x-user-id"] ?? "demo-student");
const skillCatalog = ["TypeScript", "React", "Next.js", "Node.js", "Python", "SQL", "PostgreSQL", "Docker", "AWS", "System Design", "Communication", "Git"];
const extractSkills = (text: string) => skillCatalog.filter((skill) => text.toLowerCase().includes(skill.toLowerCase()));
const skillBadges = [{ key: "typescript-verified", name: "TypeScript Verified", icon: "🔷", description: "Verified TypeScript capability", skillName: "TypeScript" }, { key: "react-verified", name: "React Verified", icon: "⚛️", description: "Verified React capability", skillName: "React" }, { key: "python-verified", name: "Python Verified", icon: "🐍", description: "Verified Python capability", skillName: "Python" }, { key: "sql-verified", name: "SQL Verified", icon: "🗄️", description: "Verified SQL capability", skillName: "SQL" }, { key: "aws-verified", name: "AWS Verified", icon: "☁️", description: "Verified AWS capability", skillName: "AWS" }, { key: "docker-verified", name: "Docker Verified", icon: "🐳", description: "Verified Docker capability", skillName: "Docker" }, { key: "system-design-verified", name: "System Design Verified", icon: "🏗️", description: "Verified system design capability", skillName: "System Design" }, { key: "communication-verified", name: "Communication Verified", icon: "💬", description: "Verified communication capability", skillName: "Communication" }, { key: "git-verified", name: "Git Verified", icon: "🌿", description: "Verified Git capability", skillName: "Git" }];
const verifySkills = async (studentId: string, skills: string[], sourceType: string) => { const known = skillBadges.filter((badge) => skills.some((skill) => skill.toLowerCase() === badge.skillName.toLowerCase())); const awarded = []; for (const badge of known) { await prisma.studentSkill.upsert({ where: { studentId_skill: { studentId, skill: badge.skillName } }, update: { level: "EXPERT", score: 100, verified: true }, create: { studentId, skill: badge.skillName, level: "EXPERT", score: 100, verified: true } }); const result = await prisma.studentBadge.upsert({ where: { studentId_badgeId: { studentId, badgeId: (await prisma.skillBadge.findUniqueOrThrow({ where: { key: badge.key } })).id } }, update: {}, create: { studentId, badgeId: (await prisma.skillBadge.findUniqueOrThrow({ where: { key: badge.key } })).id, sourceType }, include: { badge: true } }); if (result.earnedAt.getTime() >= Date.now() - 1000) awarded.push(result.badge); } return awarded; };
const report = (type: string, title: string, payload: object) => ({ type, title, payload, generatedAt: new Date().toISOString() });
app.post("/api/ai/resume/analyze", upload.single("resume"), async (req, res) => {
  if (!req.file) return res.status(400).json({ message: "A resume file is required" });
  const text = `${req.file.originalname} ${String(req.body.text ?? "")}`;
  const skills = extractSkills(text); const missing = skillCatalog.filter((skill) => !skills.includes(skill));
  if (process.env.DATABASE_URL) await verifySkills(userIdFromRequest(req), skills, "RESUME_VERIFIED");
  const result = report("RESUME", "Resume intelligence report", { atsScore: Math.min(96, 48 + skills.length * 4), roleMatch: Math.min(94, 35 + skills.length * 5), skills, missingSkills: missing.slice(0, 6), education: [], projects: [], experience: [] });
  res.status(201).json(result);
});
app.post("/api/ai/curriculum/analyze", upload.single("syllabus"), async (req, res) => {
  if (!req.file) return res.status(400).json({ message: "A syllabus PDF is required" });
  const text = `${req.file.originalname} ${String(req.body.text ?? "")}`; const found = extractSkills(text);
  res.status(201).json(report("CURRICULUM", "Curriculum intelligence report", { industryMatch: Math.min(100, 42 + found.length * 7), missingTopics: ["Cloud deployment", "Observability", "Secure API design"], outdatedTopics: ["Legacy server-rendered patterns"], recommendedModules: ["Production TypeScript", "Cloud-native systems", "Applied AI delivery"], radar: { labels: ["Frontend", "Backend", "Cloud", "Data", "AI"], current: [72, 64, 38, 46, 31], industry: [85, 82, 76, 70, 68] } }));
});
app.post("/api/ai/skill-gap", async (req, res) => { const required = Array.isArray(req.body.requiredSkills) ? req.body.requiredSkills : ["TypeScript", "React", "AWS", "System Design"]; const current = Array.isArray(req.body.studentSkills) ? req.body.studentSkills : ["TypeScript", "React"]; const gaps = required.filter((skill: string) => !current.includes(skill)); res.json(report("SKILL_GAP", "Skill gap analysis", { gapPercent: Math.round((gaps.length / Math.max(required.length, 1)) * 100), currentSkills: current, requiredSkills: required, gaps, learningPath: gaps.map((skill: string, index: number) => ({ order: index + 1, skill, durationWeeks: 3 })) })); });
app.get("/api/ai/recommendations", async (_req, res) => res.json({ recommendations: [{ kind: "COURSE", title: "Production TypeScript", reason: "Builds the strongest gap for modern product teams", priority: 1 }, { kind: "PROJECT", title: "Industry skills intelligence dashboard", reason: "Demonstrates applied data and product thinking", priority: 2 }, { kind: "PRACTICE", title: "System design interview set", reason: "Improves readiness for target engineering roles", priority: 3 }] }));
app.get("/api/ai/trends", async (req, res) => { const months = Number(req.query.months ?? 6); res.json({ horizonMonths: months, trends: [{ skill: "AI Engineering", demand: 94, growth: "+38%" }, { skill: "Cloud Security", demand: 87, growth: "+26%" }, { skill: "Platform Engineering", demand: 82, growth: "+21%" }, { skill: "Data Engineering", demand: 79, growth: "+18%" }] }); });
const regions = [
  { state: "Karnataka", district: "Bengaluru Urban", industry: "Technology", enrollments: 18400, openRoles: 12600, shortageIndex: 82, medianSalary: 950000, experienceYears: 2 },
  { state: "Telangana", district: "Hyderabad", industry: "Technology", enrollments: 14200, openRoles: 9800, shortageIndex: 74, medianSalary: 820000, experienceYears: 2 },
  { state: "Maharashtra", district: "Pune", industry: "Manufacturing", enrollments: 11600, openRoles: 8700, shortageIndex: 69, medianSalary: 720000, experienceYears: 3 },
  { state: "Tamil Nadu", district: "Chennai", industry: "Automotive", enrollments: 9800, openRoles: 7600, shortageIndex: 77, medianSalary: 680000, experienceYears: 2 },
  { state: "Delhi", district: "New Delhi", industry: "Services", enrollments: 15900, openRoles: 11200, shortageIndex: 63, medianSalary: 790000, experienceYears: 2 },
  { state: "Gujarat", district: "Ahmedabad", industry: "Manufacturing", enrollments: 8300, openRoles: 6400, shortageIndex: 71, medianSalary: 610000, experienceYears: 3 }
];
app.get("/api/industry/heatmap", async (req, res) => { const industry = String(req.query.industry ?? "ALL"); const minSalary = Number(req.query.minSalary ?? 0); const maxExperience = Number(req.query.maxExperience ?? 99); const filtered = regions.filter((region) => (industry === "ALL" || region.industry === industry) && region.medianSalary >= minSalary && region.experienceYears <= maxExperience); res.json({ regions: filtered, ranking: [...filtered].sort((a, b) => b.shortageIndex - a.shortageIndex), filters: { industries: ["ALL", "Technology", "Manufacturing", "Automotive", "Services"] } }); });
const fallbackCollaborations = [{ companyName: "Bharat Cloud Systems", industry: "Technology", type: "APPRENTICESHIP", description: "Cloud operations cohort for final-year students", status: "APPROVED" }, { companyName: "Mitra Mobility", industry: "Automotive", type: "MICRO_PROJECT", description: "Predictive maintenance analytics challenge", status: "PENDING" }];
app.get("/api/industry/collaborations", async (_req, res) => { if (!process.env.DATABASE_URL) return res.json({ collaborations: fallbackCollaborations }); const collaborations = await prisma.collaboration.findMany({ orderBy: { createdAt: "desc" } }); res.json({ collaborations }); });
app.post("/api/industry/collaborations", async (req, res) => { const body = req.body as Record<string, unknown>; if (!body.companyName || !body.type || !body.description) return res.status(400).json({ message: "companyName, type and description are required" }); if (!process.env.DATABASE_URL) { const record = { id: `collab-${Date.now()}`, companyName: String(body.companyName), industry: String(body.industry ?? "Technology"), type: String(body.type), description: String(body.description), status: "PENDING" }; fallbackCollaborations.unshift(record); return res.status(201).json(record); } const collaboration = await prisma.collaboration.create({ data: { companyName: String(body.companyName), industry: String(body.industry ?? "Technology"), type: String(body.type), description: String(body.description) } }); res.status(201).json(collaboration); });
app.post("/api/industry/surveys", async (req, res) => { const body = req.body as Record<string, unknown>; if (!body.businessName || !body.phone || !body.district || !body.industry) return res.status(400).json({ message: "Business, phone, district and industry are required" }); const hiringDemand = Number.isFinite(Number(body.hiringDemand)) ? Number(body.hiringDemand) : 0; const requiredSkills = Array.isArray(body.requiredSkills) ? body.requiredSkills : []; if (!process.env.DATABASE_URL) return res.status(201).json({ id: `survey-${Date.now()}`, ...body, hiringDemand, requiredSkills, source: body.source ?? "PORTAL", receivedAt: new Date().toISOString() }); const survey = await prisma.msmeSurvey.create({ data: { businessName: String(body.businessName), phone: String(body.phone), district: String(body.district), industry: String(body.industry), hiringDemand, requiredSkills, source: String(body.source ?? "PORTAL") } }); res.status(201).json(survey); });
app.get("/api/industry/apprenticeships/matches", async (req, res) => { const district = String(req.query.district ?? "Bengaluru Urban"); const skills = String(req.query.skills ?? "React,TypeScript").split(",").map((skill) => skill.trim().toLowerCase()); const opportunities = [{ companyName: "Bharat Cloud Systems", title: "Cloud Engineering Apprentice", district: "Bengaluru Urban", skills: ["AWS", "TypeScript", "Docker"], openings: 12, stipend: 28000 }, { companyName: "Mitra Mobility", title: "Data Platform Apprentice", district: "Pune", skills: ["Python", "SQL", "Docker"], openings: 8, stipend: 24000 }, { companyName: "Nava Fintech", title: "Frontend Intern", district: "Bengaluru Urban", skills: ["React", "TypeScript", "Next.js"], openings: 6, stipend: 22000 }].map((opportunity) => ({ ...opportunity, score: Math.round((opportunity.skills.filter((skill) => skills.includes(skill.toLowerCase())).length / opportunity.skills.length) * 100), nearby: opportunity.district === district })).sort((a, b) => Number(b.nearby) - Number(a.nearby) || b.score - a.score); res.json({ opportunities }); });
app.get("/api/industry/bounties", async (_req, res) => res.json({ bounties: [{ id: "bounty-1", companyName: "Nava Fintech", title: "Build a secure onboarding flow", skill: "Next.js", reward: 15000, status: "OPEN" }, { id: "bounty-2", companyName: "Mitra Mobility", title: "Predictive maintenance dashboard", skill: "Python", reward: 25000, status: "OPEN" }] }));
app.post("/api/industry/bounties/:bountyId/apply", async (req, res) => { if (!["bounty-1", "bounty-2"].includes(req.params.bountyId)) return res.status(404).json({ message: "Bounty not found" }); res.json({ bountyId: req.params.bountyId, status: "APPLIED", message: "Application submitted" }); });
app.get("/api/success/skill-passport", async (req, res) => { if (!process.env.DATABASE_URL) return res.json({ verifiedSkills: [], badges: [], storage: "postgresql-required" }); const studentId = userIdFromRequest(req); const [skills, badges] = await Promise.all([prisma.studentSkill.findMany({ where: { studentId, verified: true }, orderBy: { skill: "asc" } }), prisma.studentBadge.findMany({ where: { studentId }, orderBy: { earnedAt: "desc" }, include: { badge: true } })]); res.json({ verifiedSkills: skills, badges }); });
app.post("/api/success/skills/verify", async (req, res) => { const skills = Array.isArray(req.body.skills) ? req.body.skills.filter((skill: unknown): skill is string => typeof skill === "string") : []; if (!skills.length) return res.status(400).json({ message: "skills must be a non-empty array" }); if (!process.env.DATABASE_URL) return res.json({ newlyAwarded: [], storage: "postgresql-required" }); const newlyAwarded = await verifySkills(userIdFromRequest(req), skills, "RESUME_VERIFIED"); res.json({ newlyAwarded }); });
app.get("/api/success/overview", async (req, res) => { const badges = process.env.DATABASE_URL ? await prisma.studentBadge.findMany({ where: { studentId: userIdFromRequest(req) }, orderBy: { earnedAt: "desc" }, include: { badge: true } }) : []; const activity = process.env.DATABASE_URL ? await prisma.codeRun.findMany({ where: { studentId: userIdFromRequest(req), createdAt: { gte: new Date(Date.now() - 30 * 86400000) } }, select: { language: true, status: true, createdAt: true } }) : []; const codingPractice = process.env.DATABASE_URL ? aggregateCodeActivity(activity).successRate : 0; const streak = process.env.DATABASE_URL ? (await prisma.codeRun.findMany({ where: { studentId: userIdFromRequest(req), createdAt: { gte: new Date(Date.now() - 365 * 86400000) } }, select: { language: true, status: true, createdAt: true } }).then(aggregateCodeActivity)).currentStreak : 0; res.json({ xp: 2840, coins: 460, level: 8, streak, weeklyProgress: 74, badges: badges.map((item) => ({ name: item.badge.name, icon: item.badge.icon })), activity: [{ label: "GitHub activity", value: 86 }, { label: "Coding practice", value: codingPractice }, { label: "Learning hours", value: 74 }, { label: "Portfolio strength", value: 92 }] }); });
app.get("/api/success/tasks", async (_req, res) => res.json({ tasks: [{ id: "task-1", title: "Solve 2 array problems", category: "Coding", xp: 80, completed: false }, { id: "task-2", title: "Finish System Design lesson", category: "Learning", xp: 60, completed: true }, { id: "task-3", title: "Push one documented project commit", category: "Portfolio", xp: 100, completed: false }, { id: "task-4", title: "Review one interview question", category: "Interview", xp: 40, completed: false }] }));
app.post("/api/success/tasks/:taskId/complete", async (req, res) => res.json({ taskId: req.params.taskId, completed: true, xpAwarded: 80, message: "Task completed and XP awarded" }));
app.get("/api/success/recommendations", async (_req, res) => res.json({ courses: [{ title: "Free Full-Stack TypeScript", provider: "SkillSync Academy", match: 96 }, { title: "AWS Cloud Practitioner", provider: "AWS Educate", match: 88 }], projects: [{ title: "Build an industry demand dashboard", skills: "Next.js · Data visualization", reward: "Portfolio" }, { title: "Create a secure auth service", skills: "Node.js · JWT · PostgreSQL", reward: "Portfolio" }] }));
app.get("/api/success/leaderboard", async (_req, res) => res.json({ leaders: [{ rank: 1, name: "Riya Sharma", xp: 4620, level: 12 }, { rank: 2, name: "Aarav Kapoor", xp: 2840, level: 8 }, { rank: 3, name: "Dev Mehta", xp: 2710, level: 8 }] }));
app.get("/api/success/mentor", async (_req, res) => res.json({ message: "You are 2 focused tasks away from completing this week’s readiness goal. Start with the array problems, then document your latest project commit.", nextAction: "Open daily tasks" }));
app.get("/api/notifications", async (_req, res) => res.json({ notifications: [{ id: "notification-1", channel: "PUSH", title: "Your weekly readiness report is ready", read: false, createdAt: new Date().toISOString() }, { id: "notification-2", channel: "EMAIL", title: "New apprenticeship match in Bengaluru", read: false, createdAt: new Date().toISOString() }] }));
app.post("/api/notifications/:id/read", async (req, res) => res.json({ id: req.params.id, read: true }));
app.post("/api/notifications/send", async (req, res) => { const body = req.body as Record<string, unknown>; const channel = String(body.channel ?? "PUSH"); if (!["EMAIL", "SMS", "WHATSAPP", "PUSH"].includes(channel)) return res.status(400).json({ message: "Unsupported notification channel" }); res.status(202).json({ status: "QUEUED", channel, message: "Notification queued for delivery" }); });
app.get("/api/admin/audit-logs", async (_req, res) => res.json({ logs: [{ action: "AI_REPORT_GENERATED", actor: "student@skillsync.ai", resource: "resume-report", at: new Date().toISOString() }, { action: "INDUSTRY_FILTER_USED", actor: "admin@skillsync.ai", resource: "heatmap", at: new Date().toISOString() }] }));
const bridgeJobs = [{ id: "job-1", title: "Frontend Engineer", company: "Nava Fintech", type: "FULL_TIME", location: "Bengaluru", salary: "₹12–18 LPA", experience: "1–3 years", required: ["React", "TypeScript", "Next.js", "Testing"], preferred: ["AWS", "System Design"], projects: 1, certifications: 0 }, { id: "job-2", title: "Cloud Engineering Apprentice", company: "Bharat Cloud Systems", type: "APPRENTICESHIP", location: "Bengaluru", salary: "₹28,000/month", experience: "0–1 years", required: ["TypeScript", "Docker", "AWS"], preferred: ["Linux", "PostgreSQL"], projects: 1, certifications: 0 }, { id: "job-3", title: "Data Platform Intern", company: "Mitra Mobility", type: "INTERNSHIP", location: "Pune", salary: "₹24,000/month", experience: "0–1 years", required: ["Python", "SQL", "Docker"], preferred: ["AWS"], projects: 1, certifications: 0 }];
const bridgeStudentSkills = ["React", "TypeScript", "Next.js", "SQL", "Git", "Communication"];
const calculateBridgeMatch = (job: typeof bridgeJobs[number]) => { const matched = job.required.filter((skill) => bridgeStudentSkills.includes(skill)); const missing = job.required.filter((skill) => !bridgeStudentSkills.includes(skill)); const skillMatch = Math.round(matched.length / job.required.length * 100); return { job, overall: Math.max(0, skillMatch - missing.length * 3 + 8), skillMatch, technical: skillMatch, project: job.projects ? 82 : 55, certification: job.certifications ? 70 : 58, experience: 72, missing: missing.map((skill) => ({ skill, priority: matched.length < 2 ? "CRITICAL" : "IMPORTANT", category: "TECHNICAL" })) }; };
const companyCandidates = (jobId: string) => { const item = bridgeJobs.map(calculateBridgeMatch).find((match) => match.job.id === jobId); if (!item) return null; return { candidates: [{ name: "Aarav Kapoor", match: item.overall, category: item.overall > 75 ? "BEST_MATCH" : "HIGH_POTENTIAL", assessment: 86, projects: 2, certifications: 1, experience: 1 }, { name: "Riya Sharma", match: Math.max(0, item.overall - 8), category: "GOOD_MATCH", assessment: 91, projects: 1, certifications: 2, experience: 1 }] }; };
app.get("/api/opportunities", async (req, res) => { const query = String(req.query.search ?? "").toLowerCase().trim(); const type = String(req.query.type ?? "ALL"); const matches = bridgeJobs.map(calculateBridgeMatch).filter((item) => (!query || `${item.job.title} ${item.job.company} ${item.job.location} ${item.job.required.join(" ")}`.toLowerCase().includes(query)) && (type === "ALL" || item.job.type === type)); const studentId = userIdFromRequest(req); const applications = process.env.DATABASE_URL && matches.length ? await prisma.application.findMany({ where: { studentId, jobId: { in: matches.map((item) => item.job.id) } }, select: { jobId: true } }) : []; const applied = new Set(applications.map((application) => application.jobId)); res.json({ opportunities: matches.map((item) => ({ id: item.job.id, title: item.job.title, company: item.job.company, location: item.job.location, salary: item.job.salary, experience: item.job.experience, match: item.overall, type: item.job.type, applied: applied.has(item.job.id) })), filters: ["ALL", "FULL_TIME", "INTERNSHIP", "APPRENTICESHIP"] }); });
app.post("/api/opportunities/:jobId/apply", async (req, res) => { const job = bridgeJobs.find((item) => item.id === req.params.jobId); if (!job) return res.status(404).json({ message: "Opportunity not found" }); const studentId = userIdFromRequest(req); if (!process.env.DATABASE_URL) return res.status(201).json({ applicationId: `application-${Date.now()}`, jobId: job.id, status: "APPLIED", message: "Application submitted successfully" }); const application = await prisma.application.upsert({ where: { studentId_jobId: { studentId, jobId: job.id } }, update: { status: "APPLIED" }, create: { studentId, jobId: job.id, status: "APPLIED" } }); res.status(201).json({ applicationId: application.id, jobId: job.id, status: application.status, message: "Application submitted successfully" }); });
app.get("/api/company/profile", async (req, res) => { if (!process.env.DATABASE_URL) return res.json({ profile: null }); const profile = await prisma.companyProfile.findUnique({ where: { userId: userIdFromRequest(req) } }); res.json({ profile }); });
app.post("/api/company/profile", async (req, res) => { const body = req.body as Record<string, unknown>; if (!String(body.companyName ?? "").trim() || !String(body.industry ?? "").trim()) return res.status(400).json({ message: "companyName and industry are required" }); if (!process.env.DATABASE_URL) return res.status(201).json({ profile: { id: `company-${Date.now()}`, userId: userIdFromRequest(req), companyName: String(body.companyName), industry: String(body.industry), description: body.description ? String(body.description) : null } }); const profile = await prisma.companyProfile.upsert({ where: { userId: userIdFromRequest(req) }, update: { companyName: String(body.companyName), industry: String(body.industry), description: body.description ? String(body.description) : null }, create: { userId: userIdFromRequest(req), companyName: String(body.companyName), industry: String(body.industry), description: body.description ? String(body.description) : null } }); res.status(201).json({ profile }); });
app.get("/api/company/dashboard", async (req, res) => { const profile = process.env.DATABASE_URL ? await prisma.companyProfile.findUnique({ where: { userId: userIdFromRequest(req) } }) : null; const collaborations = process.env.DATABASE_URL && profile ? await prisma.collaboration.findMany({ where: { companyName: profile.companyName }, orderBy: { createdAt: "desc" } }) : fallbackCollaborations; res.json({ postedJobs: bridgeJobs.map((job) => ({ id: job.id, title: job.title, type: job.type, location: job.location, openings: job.required.length })), totalCandidatesRanked: bridgeJobs.reduce((total, job) => total + (companyCandidates(job.id)?.candidates.length ?? 0), 0), collaborations }); });
app.get("/api/company/candidates/:jobId", async (req, res) => { const result = companyCandidates(req.params.jobId); if (!result) return res.status(404).json({ message: "Job not found" }); res.json(result); });
app.get("/api/bridge/jobs", async (req, res) => { const query = String(req.query.search ?? "").toLowerCase(); const type = String(req.query.type ?? "ALL"); const jobs = bridgeJobs.map(calculateBridgeMatch).filter((item) => (!query || `${item.job.title} ${item.job.company} ${item.job.required.join(" ")}`.toLowerCase().includes(query)) && (type === "ALL" || item.job.type === type)); res.json({ jobs, filters: ["ALL", "FULL_TIME", "INTERNSHIP", "APPRENTICESHIP"] }); });
app.get("/api/bridge/matches/:jobId", async (req, res) => { const item = bridgeJobs.map(calculateBridgeMatch).find((match) => match.job.id === req.params.jobId); if (!item) return res.status(404).json({ message: "Job not found" }); res.json({ ...item, roadmap: { estimatedWeeks: item.missing.length * 3 + 2, difficulty: item.missing.length > 2 ? "Advanced" : "Intermediate", progress: 34, steps: ["Learn missing skill", "Complete course", "Build a proof project", "Take assessment", "Earn certificate", "Recalculate match"] } }); });
app.post("/api/bridge/jobs/:jobId/apply", async (req, res) => { const item = bridgeJobs.find((job) => job.id === req.params.jobId); if (!item) return res.status(404).json({ message: "Job not found" }); res.status(201).json({ applicationId: `application-${Date.now()}`, jobId: item.id, status: "APPLIED", message: "Application submitted successfully" }); });
app.get("/api/bridge/candidate-ranking/:jobId", async (req, res) => { const item = bridgeJobs.map(calculateBridgeMatch).find((match) => match.job.id === req.params.jobId); if (!item) return res.status(404).json({ message: "Job not found" }); res.json({ candidates: [{ name: "Aarav Kapoor", match: item.overall, category: item.overall > 75 ? "BEST_MATCH" : "HIGH_POTENTIAL", assessment: 86, projects: 2, certifications: 1, experience: 1 }, { name: "Riya Sharma", match: Math.max(0, item.overall - 8), category: "GOOD_MATCH", assessment: 91, projects: 1, certifications: 2, experience: 1 }] }); });
app.get("/api/bridge/recommendations", async (_req, res) => res.json({ courses: [{ title: "AWS Cloud Practitioner", skill: "AWS", reason: "Raises eligibility for 2 target roles", priority: "CRITICAL" }, { title: "Practical Testing with React", skill: "Testing", reason: "Closes a high-weight requirement", priority: "IMPORTANT" }], projects: [{ title: "Deploy a production Next.js app", skills: ["AWS", "Docker"], impact: "+12 match points" }] }));
app.get("/api/docs", (_req, res) => res.json({ openapi: "3.0.3", info: { title: "SkillSync AI API", version: "1.0.0" }, servers: [{ url: "http://localhost:4000" }], paths: { "/api/health": { get: { summary: "Health check" } }, "/api/ai/resume/analyze": { post: { summary: "Analyze resume" } }, "/api/industry/heatmap": { get: { summary: "Regional demand heatmap" } }, "/api/success/tasks": { get: { summary: "Student tasks" } }, "/api/notifications/send": { post: { summary: "Queue a notification" } } } }));
app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => { const message = err instanceof Error ? err.message : "Unexpected error"; res.status(400).json({ message }); });
const port = Number(process.env.PORT ?? 4000); app.listen(port, () => { console.log(`SkillSync API listening on ${port}`); if (process.env.DATABASE_URL) void Promise.all(skillBadges.map((badge) => prisma.skillBadge.upsert({ where: { key: badge.key }, update: { name: badge.name, icon: badge.icon, description: badge.description, skillName: badge.skillName }, create: badge }))).catch((error) => console.error("Skill badge seed failed", error)); });
